"use client";

import Link from "next/link";
import ReactMarkdown from "react-markdown";
import type { ActionCard } from "@/lib/api";
import { ClaimRef } from "./EvidenceDrawer";

const KIND: Record<ActionCard["kind"], string> = {
  evidence_brief: "Evidence brief",
  outreach_note: "Outreach note",
  asset_reuse: "Reuse an existing asset",
  gap_followup: "Gap follow-up",
  simulation_report: "Workflow simulation",
};

const FOOTNOTE = /\[\^c:([^\]\s]+)\]/g;

export function ActionCardView({ card, simulationHref }: { card: ActionCard; simulationHref?: string }) {
  const order = [...new Set([...card.body_markdown.matchAll(FOOTNOTE)].map((m) => m[1]))];
  const md = card.body_markdown.replace(FOOTNOTE, (_, id) => `[${order.indexOf(id) + 1}](#claim=${id})`);

  const download = () => {
    const refs = order.map((id, i) => `[${i + 1}] ${id}`).join("\n");
    const text = `# ${KIND[card.kind]}\n\nThis week: ${card.this_week}\nReviewed and sent by: ${card.responsible_human}\n\n${card.body_markdown.replace(FOOTNOTE, (_, id) => `[${order.indexOf(id) + 1}]`)}\n\n## Sources\n${refs}\n\n## Limitations\n${card.limitations.map((l) => `- ${l}`).join("\n")}\n\nGenerated by ${card.generated_by}. Research support only; not a clinical recommendation.\n`;
    const url = URL.createObjectURL(new Blob([text], { type: "text/markdown" }));
    const a = Object.assign(document.createElement("a"), { href: url, download: `${card.card_id.replace(":", "-")}.md` });
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <article className="rounded-md border border-rule bg-white">
      <header className="flex flex-wrap items-baseline justify-between gap-2 border-b border-rule px-4 py-2.5">
        <h3 className="font-semibold">{KIND[card.kind]}</h3>
        <span className="text-xs text-muted">for {card.audience === "family" ? "families" : "researchers"}</span>
      </header>
      <div className="space-y-3 px-4 py-3">
        <p className="text-[15px]">
          <span className="font-semibold">This week:</span> {card.this_week}
        </p>
        <div className="text-[15px] leading-relaxed text-ink/90 [&_p]:my-1">
          <ReactMarkdown
            components={{
              a: ({ href, children }) =>
                href?.startsWith("#claim=") ? (
                  <ClaimRef id={href.slice(7)} n={Number(String(children))} />
                ) : (
                  <a className="ref" href={href}>{children}</a>
                ),
            }}
          >
            {md}
          </ReactMarkdown>
        </div>
        {card.contact && (
          <p className="text-sm">
            Contact route: <a className="ref" href={card.contact.url} target="_blank" rel="noreferrer">{card.contact.label}</a>
            <span className="text-muted"> (public page, checked {card.contact.verified_at})</span>
          </p>
        )}
        <ul className="list-disc pl-5 text-sm text-muted">
          {[...card.reuse_limits, ...card.limitations].map((l) => <li key={l}>{l}</li>)}
        </ul>
      </div>
      <footer className="flex flex-wrap items-center justify-between gap-2 border-t border-rule bg-page/60 px-4 py-2 text-sm">
        <span className="text-muted">A {card.responsible_human} reviews this before it is used.</span>
        <span className="flex gap-3">
          {simulationHref && <Link className="ref font-medium" href={simulationHref}>Open simulation</Link>}
          <button onClick={download} className="font-medium text-link hover:underline">Download .md</button>
        </span>
      </footer>
    </article>
  );
}
