import type { ReactNode } from "react";
import { ClaimChip } from "@/components/EvidenceDrawer";
import { footnoteOrder } from "@/lib/cards";
import { PREDICATE_PLAIN } from "@/lib/labels";

// A deliberately small renderer for action cards: headings, bullets, **bold**, `code` and [^c:CLAIM] footnotes.
// Card text is generated by our own templates from stored claims; it is rendered as text, never as HTML.

function inline(text: string, order: string[]): ReactNode[] {
  const parts: ReactNode[] = [];
  const re = /(\[\^c:[^\]\s]+\]|\*\*[^*]+\*\*|`[^`]+`)/g;
  let last = 0;
  let k = 0;
  for (const m of text.matchAll(re)) {
    const at = m.index ?? 0;
    if (at > last) parts.push(text.slice(last, at));
    const tok = m[0];
    if (tok.startsWith("[^c:")) {
      const id = tok.slice(4, -1);
      parts.push(<ClaimChip key={k++} id={id} n={order.indexOf(id) + 1} />);
    } else if (tok.startsWith("**")) parts.push(<strong key={k++}>{tok.slice(2, -2)}</strong>);
    else {
      const code = tok.slice(1, -1);
      parts.push(
        <code key={k++} className="font-mono text-[11px]">
          {PREDICATE_PLAIN[code] ?? code}
        </code>,
      );
    }
    last = at + tok.length;
  }
  if (last < text.length) parts.push(text.slice(last));
  return parts;
}

export function Markdown({ md }: { md: string }) {
  const order = footnoteOrder(md);
  const blocks: ReactNode[] = [];
  let list: string[] = [];
  const flush = () => {
    if (list.length)
      blocks.push(
        <ul key={`l${blocks.length}`} className="my-1.5 list-disc space-y-0.5 pl-5">
          {list.map((x, i) => (
            <li key={i}>{inline(x, order)}</li>
          ))}
        </ul>,
      );
    list = [];
  };
  for (const line of md.split("\n")) {
    const bullet = /^\s*[-*]\s+(.*)$/.exec(line);
    if (bullet) {
      list.push(bullet[1] as string);
      continue;
    }
    flush();
    const h = /^(#{1,3})\s+(.*)$/.exec(line);
    if (h) {
      if ((h[1] as string).length > 1)
        blocks.push(
          <h4 key={blocks.length} className="mt-3 text-xs font-semibold">
            {inline(h[2] as string, order)}
          </h4>,
        );
      continue;
    }
    if (line.trim())
      blocks.push(
        <p key={blocks.length} className="my-1.5">
          {inline(line, order)}
        </p>,
      );
  }
  flush();
  return <div className="text-xs leading-6">{blocks}</div>;
}
