/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClustersRouteImport } from './routes/clusters'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as SymptomsRouteImport } from './routes/symptoms'
import { Route as EntityIdRouteImport } from './routes/entity.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClustersRoute = ClustersRouteImport.update({
  id: '/clusters',
  path: '/clusters',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomsRoute = SymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const EntityIdRoute = EntityIdRouteImport.update({
  id: '/entity/$id',
  path: '/entity/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/explorer': typeof ExplorerRoute
  '/simulation': typeof SimulationRoute
  '/symptoms': typeof SymptomsRoute
  '/entity/$id': typeof EntityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/explorer': typeof ExplorerRoute
  '/simulation': typeof SimulationRoute
  '/symptoms': typeof SymptomsRoute
  '/entity/$id': typeof EntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clusters': typeof ClustersRoute
  '/explorer': typeof ExplorerRoute
  '/simulation': typeof SimulationRoute
  '/symptoms': typeof SymptomsRoute
  '/entity/$id': typeof EntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clusters'
    | '/explorer'
    | '/simulation'
    | '/symptoms'
    | '/entity/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clusters'
    | '/explorer'
    | '/simulation'
    | '/symptoms'
    | '/entity/$id'
  id:
    | '__root__'
    | '/'
    | '/clusters'
    | '/explorer'
    | '/simulation'
    | '/symptoms'
    | '/entity/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClustersRoute: typeof ClustersRoute
  ExplorerRoute: typeof ExplorerRoute
  SimulationRoute: typeof SimulationRoute
  SymptomsRoute: typeof SymptomsRoute
  EntityIdRoute: typeof EntityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clusters': {
      id: '/clusters'
      path: '/clusters'
      fullPath: '/clusters'
      preLoaderRoute: typeof ClustersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptoms': {
      id: '/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof SymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entity/$id': {
      id: '/entity/$id'
      path: '/entity/$id'
      fullPath: '/entity/$id'
      preLoaderRoute: typeof EntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClustersRoute: ClustersRoute,
  ExplorerRoute: ExplorerRoute,
  SimulationRoute: SimulationRoute,
  SymptomsRoute: SymptomsRoute,
  EntityIdRoute: EntityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
