import type { ActionCard } from "@/lib/api";

const FOOTNOTE = /\[\^c:([^\]\s]+)\]/g;

export function footnoteOrder(md: string): string[] {
  return [...new Set([...md.matchAll(FOOTNOTE)].map((m) => m[1] as string))];
}

export const KIND: Record<ActionCard["kind"], string> = {
  evidence_brief: "Evidence brief",
  outreach_note: "Outreach note",
  asset_reuse: "Reuse an existing asset",
  gap_followup: "Gap follow-up",
  simulation_report: "Workflow simulation",
};

const FOOT = /\[\^c:([^\]\s]+)\]/g;

/** The card as a standalone Markdown file: numbered sources and the limitations travel with the text. */
export function cardToMarkdown(card: ActionCard): string {
  const order = footnoteOrder(card.body_markdown);
  const refs = order.map((id, i) => `[${i + 1}] ${id}`).join("\n");
  return `# ${KIND[card.kind]}\n\nThis week: ${card.this_week}\nReviewed and sent by: ${card.responsible_human}\n\n${card.body_markdown.replace(FOOT, (_, id: string) => `[${order.indexOf(id) + 1}]`)}\n\n## Sources\n${refs}\n\n## Limitations\n${card.limitations.map((l) => `- ${l}`).join("\n")}\n\nGenerated by ${card.generated_by}. Research support only; not a clinical recommendation.\n`;
}
